// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0Y6JOEvuJrRKKrpoO2hIT0BEVfgviss',
    appId: '1:1034489413233:web:aaa78ed6ad03bea69425d0',
    messagingSenderId: '1034489413233',
    projectId: 'jong-match-project',
    authDomain: 'jong-match-project.firebaseapp.com',
    storageBucket: 'jong-match-project.appspot.com',
    measurementId: 'G-QR1PCKJVXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHp826CYcIFqqn3VWP1FCi9gj0KVldZQ',
    appId: '1:1034489413233:android:0d6d06058574defc9425d0',
    messagingSenderId: '1034489413233',
    projectId: 'jong-match-project',
    storageBucket: 'jong-match-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeneq2u1AQCV6u3RDihGBbMBoZFSl9-6k',
    appId: '1:1034489413233:ios:b9d62aa2715f78829425d0',
    messagingSenderId: '1034489413233',
    projectId: 'jong-match-project',
    storageBucket: 'jong-match-project.appspot.com',
    iosClientId: '1034489413233-elq8r7qa5ctbb1vakbhh5gevmg41esg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.jongMatchApp',
  );
}
